name: el_mandilon_ventas
description: A Flutter application for tracking sales across cities, stores, and employees.
version: 1.0.0
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  audioplayers: ^6.1.0
  fl_chart: ^0.69.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/sounds/notification.mp3